"use client";

const STAGES = [
  {
    num: "01",
    title: "ENERGY",
    desc: "Energy is generated by the power unit.",
    icon: (
      <svg className="w-5 h-5 text-[#007F91]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <circle cx="12" cy="12" r="9" />
        <path d="M12 3v3m0 12v3M3 12h3m12 0h3" />
      </svg>
    ),
  },
  {
    num: "02",
    title: "WATER DISPLACEMENT",
    desc: "The surge displaces water across the lagoon.",
    icon: (
      <svg className="w-5 h-5 text-[#007F91]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M2 12c.6 0 1.2-.2 1.6-.6 1-.8 2.2-.8 3.2 0 .8.6 1.8.8 2.8.4 1-.4 2.2-.4 3.2.2.8.5 1.8.6 2.8.2 1-.4 2.2-.4 3.2.2.6.4 1.4.6 2.2.6" />
      </svg>
    ),
  },
  {
    num: "03",
    title: "WAVE FORMATION",
    desc: "The displaced water rises and forms a wave.",
    icon: (
      <svg className="w-5 h-5 text-[#007F91]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M2 16c3-4 6-8 10-8s7 4 10 8" />
      </svg>
    ),
  },
  {
    num: "04",
    title: "WAVE PROPAGATION",
    desc: "The wave travels across the lagoon.",
    icon: (
      <svg className="w-5 h-5 text-[#007F91]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M5 12h14M12 5l7 7-7 7" />
      </svg>
    ),
  },
  {
    num: "05",
    title: "SURFABLE WAVE",
    desc: "A perfect wave arrives ready to be surfed.",
    icon: (
      <svg className="w-5 h-5 text-[#007F91]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M2 12c.6 0 1.2-.2 1.6-.6 1-.8 2.2-.8 3.2 0 .8.6 1.8.8 2.8.4 1-.4 2.2-.4 3.2.2.8.5 1.8.6 2.8.2 1-.4 2.2-.4 3.2.2.6.4 1.4.6 2.2.6" />
        <circle cx="18" cy="8" r="2" />
      </svg>
    ),
  },
];

export default function MotionToWave() {
  return (
    <section id="tech-section-03" className="bg-[#F7F8F6] text-[#092531] py-14 sm:py-20 relative z-10 border-b border-slate-200/80">
      <div className="max-w-7xl mx-auto px-6 lg:px-12 text-left">
        
        <div className="max-w-2xl mb-14">
          <span className="font-mono text-xs sm:text-sm font-extrabold text-[#007F91] block mb-3">
            03
          </span>
          <h2 className="font-serif text-3xl sm:text-5xl font-bold text-[#092531] tracking-tight leading-[1.08]">
            FROM MOTION<br />TO WAVE.
          </h2>
        </div>

        {/* 5-Stage Infographic Horizontal Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-5 gap-4 items-stretch relative">
          {STAGES.map((stg, idx) => (
            <div
              key={stg.num}
              className="bg-white border border-slate-200 rounded-2xl p-5 flex flex-col justify-between shadow-sm hover:shadow-md transition-shadow relative"
            >
              <div>
                <div className="flex items-center justify-between mb-4">
                  <div className="w-9 h-9 rounded-xl bg-[#F0EEE7] flex items-center justify-center">
                    {stg.icon}
                  </div>
                  <span className="font-mono text-xs font-bold text-[#007F91]">
                    {stg.num}
                  </span>
                </div>

                <h4 className="font-sans text-xs font-extrabold uppercase tracking-wider text-[#092531] mb-2">
                  {stg.title}
                </h4>

                <p className="text-[11px] text-slate-600 leading-relaxed font-sans font-medium">
                  {stg.desc}
                </p>
              </div>

              {idx < STAGES.length - 1 && (
                <div className="hidden sm:block absolute -right-3 top-1/2 -translate-y-1/2 z-20 text-slate-400">
                  →
                </div>
              )}
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}
